-- WhoIsThis faculty seed
-- Source: KAU_Medicine_Jeddah_Faculty_Directory(1).xlsx
-- Generated from 137 spreadsheet rows.
-- One obvious duplicate person was consolidated:
--   Dr Ashraf Youssef Nasr / Prof Ashraf Youssef Nasr -> Prof Ashraf Youssef Nasr
-- Result: 136 faculty entries.
--
-- Safe to run more than once: existing exact name+department matches are skipped.

insert into public.professors (name, department, is_active)
values
  ('Prof Ashraf Youssef Nasr', 'Anatomy', true),
  ('Dr Emad Ahmed Hindi', 'Anatomy', true),
  ('Dr Mervat Mohammed Halawani', 'Anatomy', true),
  ('Dr Nisreen Abdullah Rajeh', 'Anatomy', true),
  ('Dr Rabee Fatthalla Ali Ibrahim', 'Anatomy', true),
  ('Dr Rasha Abdulrahman Alshali', 'Anatomy', true),
  ('Dr Soad Shaker Ali', 'Anatomy', true),
  ('Dr Wafaa Saadeldin Ramadan', 'Anatomy', true),
  ('Dr Abdulhameed Mohammad Ardawi', 'Anesthesiology', true),
  ('Dr Baraa Osama Tayeb', 'Anesthesiology', true),
  ('Dr Ibrahim Ahmed Abushoshah', 'Anesthesiology', true),
  ('Dr Sara Hasan Farsi', 'Anesthesiology', true),
  ('Dr Wadeeah Khalid Bahaziq', 'Anesthesiology', true),
  ('Prof Abdulaziz Mohammed Boker', 'Anesthesiology and Intensive Care', true),
  ('Dr Aliaa MohamedAlu Sabban', 'Clinical Biochemistry', true),
  ('Dr Ayman Zaky Elsamanoudy', 'Clinical Biochemistry', true),
  ('Dr Basmah Medhat Eldakhakhny', 'Clinical Biochemistry', true),
  ('Dr Khalid Hussein Ahmed', 'Clinical Biochemistry', true),
  ('Dr Taghreed Abdullah Shamrani', 'Clinical Biochemistry', true),
  ('Dr Yousry ELsayed Abulmagd Ismaeil', 'Clinical Biochemistry', true),
  ('Dr Zuhier Ahmed Awan', 'Clinical Biochemistry', true),
  ('Dr. Ghada Mohammed Ali Ajab Nour', 'Clinical Biochemistry', true),
  ('Prof Eman Mokbel Alissa', 'Clinical Biochemistry', true),
  ('Dr Abdulhadi Salem Burzangi', 'Clinical Pharmacology', true),
  ('Dr Duaa Abdullah Bafail', 'Clinical Pharmacology', true),
  ('Dr Mohammed Abdulbasit Alsieni', 'Clinical Pharmacology', true),
  ('Dr Mohammed Abdulghaffar Bazuhair', 'Clinical Pharmacology', true),
  ('Dr. Huda Mohammed Naher Al-Kuraithi', 'Clinical Pharmacology', true),
  ('Prof Ahmed Shaker Ali', 'Clinical Pharmacology', true),
  ('Dr Banan Mohammad Alamoudi', 'Community Medicine', true),
  ('Dr Mai Sadaka Kadi', 'Community Medicine', true),
  ('Dr Rajaa Mohammad Al-Raddadi', 'Community Medicine', true),
  ('Prof Bahaa Abdulrahman Abaalkhail', 'Community Medicine', true),
  ('Dr Amal Atallah Kokandi', 'Dermatology', true),
  ('Dr Logain Ghazi Alghanemi', 'Dermatology', true),
  ('Dr. Badr Sameer Khidr Zammo', 'Dermatology', true),
  ('Dr Abdullah Abdulrahman Bakhsh', 'Emergency Medicine', true),
  ('Dr Ghada Assad Merdad', 'Emergency Medicine', true),
  ('Dr. Loai Kamel Ibrahim Al-Sulaimani', 'Emergency Medicine', true),
  ('Dr Khaled Abdulraouf Yaghmour', 'Family Medicine', true),
  ('Dr Ranya Alawy Ghamri', 'Family Medicine', true),
  ('Dr Sami Hamdan Alzahrani', 'Family Medicine', true),
  ('Dr Yazeed Abdulhameed Khojah', 'Family Medicine', true),
  ('Dr. Sultan Hassan Dhafer Al-Amri', 'Family Medicine', true),
  ('Dr Dalal Sameer Alshaer', 'Genetic Medicine', true),
  ('Dr Mahmoud Nezar Almutadares', 'Genetic Medicine', true),
  ('Dr Noha Mahmoud Issa', 'Genetic Medicine', true),
  ('Dr Wisam Tahir Habhab', 'Genetic Medicine', true),
  ('Dr Adel Fahad Almarzouki', 'Hematology', true),
  ('Dr Eman Mohsin Mansory', 'Hematology', true),
  ('Dr Duaa Abdullah Bafail', 'Internal Medicine', true),
  ('Dr Mohammed A Shaikh', 'Internal Medicine', true),
  ('Dr Rahmah Abdulhadi Alsilmi', 'Internal Medicine', true),
  ('Dr Reem Ali Alzahrani', 'Internal Medicine', true),
  ('Dr Siraj Omar Wali', 'Internal Medicine', true),
  ('Dr Waleed Saleh Alghamdi', 'Internal Medicine', true),
  ('Dr. Hind Abdullah Ibrahim Al-Najashi', 'Internal Medicine', true),
  ('Dr. Marwan Rabah Baniyah Al-Hajili', 'Internal Medicine', true),
  ('Dr Abdalbagi Alfadil Musa', 'Microbiology and Clinical Immunology', true),
  ('Dr Eman Kamel Aldigs', 'Microbiology and Clinical Immunology', true),
  ('Dr Hatoon Abdullah Niyazi', 'Microbiology and Clinical Immunology', true),
  ('Dr Jawahir Ahmad Mokhtar', 'Microbiology and Clinical Immunology', true),
  ('Dr Karem Ahmed Ibrahem', 'Microbiology and Clinical Immunology', true),
  ('Dr Mohammad Hamed Alruhaili', 'Microbiology and Clinical Immunology', true),
  ('Dr Shadi A Zakai', 'Microbiology and Clinical Immunology', true),
  ('Dr. Hanouf Abdullah Mohammed Saeed Niyazi', 'Microbiology and Clinical Immunology', true),
  ('Dr. Mohammed Wanees Omair Al-Rabiah', 'Microbiology and Clinical Immunology', true),
  ('Dr Maha Maha Alawi', 'Microbiology and Medical Parasitology_Infection control', true),
  ('Dr Aysha Abdulmalek Alshareef', 'Neurology', true),
  ('Dr Mohammed Hasan Bangash', 'Neurosurgery', true),
  ('Dr Saleh Salem Baeesa', 'Neurosurgery', true),
  ('Dr Ettedal Atiyah Aljahdali', 'Obstetrics and Gynecology', true),
  ('Dr Haifaa Ahmed Mansouri', 'Obstetrics and Gynecology', true),
  ('Dr Mohammad Abdullah Alyafi', 'Obstetrics and Gynecology', true),
  ('Dr Mohammed Mazen Malak', 'Obstetrics and Gynecology', true),
  ('Dr Nashwa Fahad Aldardeir', 'Obstetrics and Gynecology', true),
  ('Dr Osama Sadeak Bajouh', 'Obstetrics and Gynecology', true),
  ('Dr Samera Fahad AlBasri', 'Obstetrics and Gynecology', true),
  ('Dr Suhaib Wael Khayat', 'Obstetrics and Gynecology', true),
  ('Prof Khalid Hussain Sait', 'Obstetrics and Gynecology', true),
  ('Prof Sharifa Ali Alsibiani', 'Obstetrics and Gynecology', true),
  ('Dr. Ahmed Abdulrahman Mohammed Basheikh', 'Ophthalmology', true),
  ('Dr. Nizar Mohammed Ali Al-Hibshi', 'Ophthalmology', true),
  ('Dr Abdullah Abid Altuwairqi', 'Orthopaedic Surgery', true),
  ('Dr Lutf Ahmed Abumunaser', 'Orthopaedic Surgery', true),
  ('Dr Mohammed Jalal Alsayyad', 'Orthopaedic Surgery', true),
  ('Dr Ahmed Ayman Habis', 'Orthopedic Surgery', true),
  ('Dr. Bashar Rehab Mahmoud Reda', 'Orthopedic Surgery', true),
  ('Dr. Haitham Reda Abdulrahman Abu Zinadah', 'Otorhinolaryngology', true),
  ('Dr. Hani Zuhair Mohammed Al-Marzouki', 'Otorhinolaryngology', true),
  ('Dr. Rana Yaqoub Ishaq Bukhari', 'Pathology', true),
  ('Dr Ahmad Taher Abdel Hafeez Ghanem', 'Pathology & Laboratory Medicine', true),
  ('Dr Awatif Ali Jamal', 'Pathology & Laboratory Medicine', true),
  ('Dr Doaa Ali Alghamdi', 'Pathology & Laboratory Medicine', true),
  ('Dr Fadwa Jameel Altaf', 'Pathology & Laboratory Medicine', true),
  ('Dr Ghadeer Ahmed Mokhtar', 'Pathology & Laboratory Medicine', true),
  ('Dr Layla Saleh Abdullah', 'Pathology & Laboratory Medicine', true),
  ('Dr Samah Nabeel Saharti', 'Pathology & Laboratory Medicine', true),
  ('Dr Sawsan Mohammad Jalalah', 'Pathology & Laboratory Medicine', true),
  ('Dr Abdulsalam O Alsulami', 'Pediatrics', true),
  ('Dr Mohammed Ahmad Nashawi', 'Pediatrics', true),
  ('Dr Naif Aowidh Alkhushi', 'Pediatrics', true),
  ('Dr Saud Abdul Aziz Bahaidarah', 'Pediatrics', true),
  ('Dr. Mishari Abdullah Mohammed Al-Aifan', 'Pediatrics', true),
  ('Dr Ashwag Ahmed Alsaidalani', 'Pediatrics_Allergy and immunology', true),
  ('Dr Esraa Mohammedomar Bukhari', 'Pediatrics_Allergy and immunology', true),
  ('Dr Duaa Mohamed Bakhshwin', 'Pharmacology & Experimental Therapeutics', true),
  ('Dr Rania Mahmoud Magadmi', 'Pharmacology & Experimental Therapeutics', true),
  ('Dr Shahid Mohammad Khalid Karim', 'Pharmacology & Experimental Therapeutics', true),
  ('Dr Abeer Fahad Almarzouki', 'Physiology', true),
  ('Dr Ebtisam Aziz Alofi', 'Physiology', true),
  ('Dr Mohamed Abd elfattah Bendary', 'Physiology', true),
  ('Dr Safa Yousef Almaghrabi', 'Physiology', true),
  ('Drﺓﺬﺷ ﻕﻮﺘﻌﻣ ﻱﺯﺍﺮﺤﻟﺍ', 'Physiology', true),
  ('Dr Yasir Abdulaziz Bahader', 'Radiation Oncology', true),
  ('Dr Ahmed Haitham Abduljabbar', 'Radiology', true),
  ('Dr Arwa Osamah Badeeb', 'Radiology', true),
  ('Dr Fadi Abdullah Toonsi', 'Radiology', true),
  ('Dr Laila Khalid Ashkar', 'Radiology', true),
  ('Dr Mawya Abdulkarim Khafaji', 'Radiology', true),
  ('Dr Mohammad A Wazzan', 'Radiology', true),
  ('Dr Nadia Abdulla Batawil', 'Radiology', true),
  ('Dr. Lamia Ghazi Abdul Latif Jamjoom', 'Radiology', true),
  ('Dr. Rani Ghazi Abdulrahman Ahmed', 'Radiology', true),
  ('Dr Khalid Ghazi Alsafi', 'Radiology_Medical Physics', true),
  ('Dr Rayan A. Ahyad', 'Radiology_Pediatric imaging', true),
  ('Dr Abdulaziz M Saleem', 'Surgery', true),
  ('Dr Abdulrahman Jafar Sabbagh', 'Surgery', true),
  ('Dr Basim Abdullah Awan', 'Surgery', true),
  ('Dr Fatma ﺲﻔﻴﻨﺧ Althoubaity', 'Surgery', true),
  ('Dr Jamal Siddiq Kamal', 'Surgery', true),
  ('Dr Nouf Yahya Akeel', 'Surgery', true),
  ('Dr Osman Osama Al-Radi', 'Surgery', true),
  ('Dr Saleh Mohammad Aldaqal', 'Surgery', true),
  ('Dr. Murad Mustafa Abdulrahman Al-Jifri', 'Surgery', true),
  ('Dr. Raed Anwar Hamed Azhar', 'Urology', true)
on conflict do nothing;

-- Verification output:
select department, count(*) as faculty_count
from public.professors
where is_active = true
group by department
order by department;
